### PR TITLE
Styling update

### PR DESCRIPTION
**Pull request by ellthompson**
Updates the styling for the jdsoc template. Before and after screenshots below:

image

image

### CODE REVIEW

**Comment by willeastcott** [comment]
Nice. LGTM!

**Comment by willeastcott** [comment]
Quick question though: how come the Index sidebar is way to the left with the updated styling?

**Review by willeastcott — APPROVED** [review]

**Comment by ellthompson** [comment]
> Quick question though: how come the Index sidebar is way to the left with the updated styling?

That's part of the new design as it declutters the main content area.

**Comment by willeastcott** [comment]
Yeah, I see that now. Great, let's goooooo! 😄

**Pull request merged**
